import {
  ArrowUp,
  Archive,
  AudioLines,
  Activity,
  BookOpen,
  Bot,
  Brain,
  Check,
  Camera,
  CalendarDays,
  CalendarClock,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  CloudSun,
  Compass,
  Code2,
  Copy,
  Database,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  FileSearch,
  Folder,
  FolderPlus,
  Globe,
  Image,
  Hammer,
  Home,
  Inbox,
  LayoutDashboard,
  ListChecks,
  Lock,
  LogOut,
  Mail,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  Moon,
  MoreHorizontal,
  Palette,
  Paperclip,
  Pause,
  Pencil,
  Play,
  Plus,
  Radio,
  RotateCcw,
  Search,
  Scissors,
  Server,
  Settings,
  Share2,
  Square,
  ShieldCheck,
  Sparkles,
  SquarePen,
  Star,
  Sun,
  Terminal,
  Target,
  Trash2,
  User,
  Users,
  Wrench,
  X,
  type LucideIcon,
} from 'lucide-react'

const icons = {
  activity: Activity,
  archive: Archive,
  attach: Paperclip,
  audioLines: AudioLines,
  bookOpen: BookOpen,
  bot: Bot,
  brain: Brain,
  calendarClock: CalendarClock,
  calendar: CalendarDays,
  camera: Camera,
  chat: MessageCircle,
  close: X,
  cloudSun: CloudSun,
  code: Code2,
  check: Check,
  compass: Compass,
  copy: Copy,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  database: Database,
  externalLink: ExternalLink,
  eye: Eye,
  eyeOff: EyeOff,
  fileSearch: FileSearch,
  fileText: FileText,
  folder: Folder,
  folderPlus: FolderPlus,
  globe: Globe,
  hammer: Hammer,
  help: CircleHelp,
  home: Home,
  inbox: Inbox,
  image: Image,
  focus: LayoutDashboard,
  listChecks: ListChecks,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  menu: Menu,
  messagesSquare: MessageSquare,
  mic: Mic,
  more: MoreHorizontal,
  moon: Moon,
  palette: Palette,
  pause: Pause,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  runtime: Server,
  search: Search,
  scissors: Scissors,
  send: ArrowUp,
  settings: Settings,
  square: Square,
  shieldCheck: ShieldCheck,
  share: Share2,
  sparkles: Sparkles,
  squarePen: SquarePen,
  statusLive: Radio,
  star: Star,
  regenerate: RotateCcw,
  sun: Sun,
  target: Target,
  terminal: Terminal,
  trash: Trash2,
  user: User,
  users: Users,
  wrench: Wrench,
} satisfies Record<string, LucideIcon>

export type AppIconName = keyof typeof icons

export function AppIcon({ name, size = 20 }: { name: AppIconName; size?: number }) {
  const Icon = icons[name]
  return <Icon aria-hidden="true" size={size} strokeWidth={1.5} />
}
